name=RFDO
version=0.0.2
author=Lautaro Ezequiel Rodriguez Base lerb.dev@gmail.com
maintainer=Lautaro Ezequiel Rodriguez Base lerb.dev@gmail.com
sentence=Library for sending and receiving data to N nRF24 devices.
paragraph=This library allows you sending and receiving data from N (max 256) devices nRF24 as a fast Half Duplex communication.
category=Communication
url=https://github.com/LautaroRodriguezBase/RFDO
architectures=*
depends=RF24
